-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfq4Zcl6tDg1mQki7
DFyocQWGp0rzI4kgqy82qsf3Wo+gCgYIKoZIzj0DAQehRANCAARNwPGN6hYVPuIq
cQsi0jBWCPkRWy0bxx+15j+NJQCpxYy1MpXrNVi2nGxiIdgSZWurn4kmcVvJOobY
Yd+VUtkQ
-----END PRIVATE KEY-----